// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationINSAT.Models;

#nullable disable

namespace WebApplicationINSAT.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20241112101822_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomersMovies", b =>
                {
                    b.Property<Guid>("CusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MoviescId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CusId", "MoviescId");

                    b.HasIndex("MoviescId");

                    b.ToTable("CustomersMovies");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Customers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Genres", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Membershiptypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<string>("DurationInMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SignUpFee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Membershiptypes");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Movies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Genre_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenresId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("CustomersMovies", b =>
                {
                    b.HasOne("WebApplicationINSAT.Models.Customers", null)
                        .WithMany()
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationINSAT.Models.Movies", null)
                        .WithMany()
                        .HasForeignKey("MoviescId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Customers", b =>
                {
                    b.HasOne("WebApplicationINSAT.Models.Membershiptypes", "Membership")
                        .WithMany("customers")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Movies", b =>
                {
                    b.HasOne("WebApplicationINSAT.Models.Genres", null)
                        .WithMany("Moviesg")
                        .HasForeignKey("GenresId");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Genres", b =>
                {
                    b.Navigation("Moviesg");
                });

            modelBuilder.Entity("WebApplicationINSAT.Models.Membershiptypes", b =>
                {
                    b.Navigation("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
